#!/bin/sh -f
#
# ---------------------------------------------------------
# LSF parameters
# ---------------------------------------------------------
#
set nonomatch
echo ""
echo "Job is running on `uname -a`"
echo "Job started on `date`"
echo ""
echo "Job has been submitted from : " $LS_SUBCWD
#if ( ${OS} != "Solaris" && ${OS} != "Linux" ) exit
#setenv OS_VERS Linux__2.6
#
#----------------------------------------------------------
# S e t t h e r u n t i m e e n v i r o n m e n t
#----------------------------------------------------------
#
echo "Step 1 : Setting the environment"
export DIR=(`pwd`)
export SCRAM_ARCH=slc6_amd64_gcc493 #CMSSW_7_6_0
export LHE=/eos/user/s/shoh/LHE/MonojetMatch1JetsDM #YOUR LHE LOCATION
export CODE_SRC=/afs/cern.ch/work/s/shoh/analysis/bb_MET_Analysis_13TeV/DarkHiggs/CMSSW_7_6_0/src/Qcut_Scan #CURRENT DIRECTORY
export ROOTFILE=/eos/user/s/shoh/Qcuts #OUTPUT LOCATION
export HADRONIZERTMPL=Hadronizer_TuneCUEP8M1_13TeV_5f_MaxJet_2_cff.py-template
export HADRONIZER=(`echo ${HADRONIZERTMPL} | awk -F "-" '{print $1}'`)
export nevent=100000
rm -rf ${CODE_SRC}/CMSSW_INPUT1_mphi_INPUT3_mchi_INPUT2_mhs_INPUT4_qcut_INPUT5.job
echo "- - - - - PATH SETTING- - - - -"
echo "SCRAM_ARCH is : " ${SCRAM_ARCH}
echo "WorkDir is : " ${WORKDIR}
echo "Disk space on this batch machine:"
#df -h
#
#----------------------------------------------------------
# Run CMSSW
#----------------------------------------------------------
#
echo "Step 2 : Run"
#####################################
# Step-1: #
#####################################
echo "Start Step-1: Generator"
cd ${WORKDIR}
scramv1 project CMSSW CMSSW_7_6_0
echo "scramv1 complete"
cd CMSSW_7_6_0/src
mkdir Configuration
cd Configuration/
mkdir users
cd users/
mkdir python/
cd python
#Copy hadronizer
cp -a ${CODE_SRC}/${HADRONIZERTMPL} .
sed s/XX_QCUT_XX/INPUT5/g ${HADRONIZERTMPL} > tmpl
mv tmpl ${HADRONIZER}
rm ${HADRONIZERTMPL}
eval `scramv1 runtime -sh`
scramv1 build
pwd
cat ${HADRONIZER}
#echo "Make sure its in CMSSW BASE"

#eval `scramv1 runtime -sh`
#scramv1 build
# Make sure compiler see the hadronizer fragment
#cd Configuration/users/python/
echo "Make sure the hadronizer in python folder"
ls
cd ../../../
scramv1 build
echo "Make sure its in CMSSW BASE"
ls
pwd

#copy nessecary files
echo "copying LHE file INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph.lhe"
cp -a ${LHE}/INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph.lhe ./INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_Qcut_INPUT5.lhe
cp ${CODE_SRC}/plotdjr.C .

#cmsDriver.py
echo "Running cmsDriver.py"
cmsDriver.py Configuration/users/python/${HADRONIZER} -s GEN --conditions auto:mc --filein file:INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_Qcut_INPUT5.lhe --fileout file:INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_pythia_Qcut_INPUT5.root -n ${nevent} --python_filename=hadronizer.py --no_exec

#setup EDMAnalyzer
#echo "Populating EDMAnalyzer"
##mkdir EDMAnalyzer
##cd EDMAnalyzer
##mkedanlzr DM_Analyzer
##cd ../
#cp -a ${SCRATCH_SRC}/CMSSW_7_6_5/src/EDMAnalyzer .
##ls ./EDMAnalyzer/DM_Analyzer/python/
#cp -a ${CODE_SRC}/analyzer_cfg.py ./EDMAnalyzer/DM_Analyzer/python/analyzer_cfg.py
#sed s/XX_FILEIN_XX/INPUT1_hadronized_Mphi_INPUT3_Mchi_INPUT2_Qcut_INPUT4.root/g ./EDMAnalyzer/DM_Analyzer/python/analyzer_cfg.py > temp
#sed s/XX_FILEOUT_XX/SAVE_INPUT1_LHE_MLM_mphi_INPUT3_mchi_INPUT2.root/g temp > temp1
#mv ./temp1 ./EDMAnalyzer/DM_Analyzer/python/analyzer_cfg.py
#rm temp
#rm temp1
#scramv1 build

#cmsRun                    
echo "cmsRun Hadronizer"
cmsRun hadronizer.py >& run.log
#echo "cmsRun EDMAnalyzer"
#cmsRun ./EDMAnalyzer/DM_Analyzer/python/analyzer_cfg.py

#Differential jet rate plots
echo "Plotting Differential Jet Rate"
root -l <<EOF
.x plotdjr.C("INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_pythia_Qcut_INPUT5.root","DJR_PLOT_INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_pythia_Qcut_INPUT5.root","INPUT5")
.q
EOF
#extracting file

echo "Copying files.."
cp run.log ${ROOTFILE}/Log/Log_INPUT1_LO_MZprime_INPUT3_Mhs_INPUT4_Mchi_INPUT2_pythia_Qcut_INPUT5.log
cp INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_pythia_Qcut_INPUT5.root ${ROOTFILE}
cp DJR_PLOT_INPUT1_LO_MZprime-INPUT3_Mhs-INPUT4_Mchi-INPUT2_gSM-0p25_gDM-1p0_th_0p01_13TeV-madgraph_pythia_Qcut_INPUT5.root ${ROOTFILE}

#
#----------------------------------------------------------
# Clear job and log
#----------------------------------------------------------
#
rm -rf ${CODE_SRC}/Log_*
rm -rf ${CODE_SRC}/LSF*
rm -rf ${CODE_SRC}/core*
rm -rf /afs/cern.ch/user/s/shoh/LSF*
cd ${WORKDIR}
rm -rf CMSSW*
echo ""
echo "Job end `date`"
echo ""
exit ${status}
